<a href="https://colab.research.google.com/github/nadireus/Clarusway/blob/main/Numpy_Assignment_1_C9224Nadire.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [ ]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [ ]:
my_list=[5,10,15,20,25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [ ]:
arraynew = np.zeros((5,5))
arraynew

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 5. Make all the values of the array above 7

In [ ]:
arrayabove7 = (np.ones((4,4)))*7
arrayabove7

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

#### 6. Create same array above with full method

In [ ]:
fullarray= np.full((4,4),7)
fullarray

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [ ]:
np.arange(2,18,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [ ]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [ ]:
np.linspace(0,25, 25,  endpoint =False, axis =0, ).reshape(5,5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

#### 10. Create 5 random number with numpy

In [ ]:
np.random.randn(5)

array([-1.77425699,  0.80749724, -0.53914992, -0.27060315, -0.71941718])

#### 11. Create random normal distributed 5x5 array

In [ ]:
np.random.randn(25).reshape(5,5)

array([[-0.3944533 , -0.75250589, -0.62449279, -0.05811686,  1.9792852 ],
       [-1.30026582,  1.3843405 , -0.24468539, -0.13577333,  0.74419333],
       [ 0.30330027,  0.47942443,  0.37220757, -0.70678324, -0.52981628],
       [ 0.91727571, -0.38091795,  0.00563102, -0.61074149, -0.25530762],
       [-0.13825384, -1.65802141,  1.26383755, -0.19199752, -0.26134561]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [ ]:
np.random.randint(20,50, size=(3,4))

array([[32, 28, 39, 26],
       [36, 21, 44, 24],
       [23, 27, 33, 36]])

#### 13. Reshape the array below with shape 6x8

In [ ]:
ranarr = np.random.randint(0, 60, 48)

In [ ]:
 a=ranarr.reshape(6,8)

In [ ]:
ranarr.reshape(6,8).T  # hocam kendime not almak icin yaptim transpozu soru ile alakasi yok :)

array([[ 0, 56, 48,  1, 27, 41],
       [10, 51, 15, 49, 32, 10],
       [22, 44,  6, 31, 22, 20],
       [49, 33, 50, 47, 46, 58],
       [ 7, 24, 50, 30, 16,  8],
       [42, 34, 18, 41, 58, 13],
       [46, 50, 42, 54, 46, 15],
       [22, 11, 41, 51, 26, 15]])

In [ ]:
a[::-1]#reshape with -1

array([[10, 55,  0,  7, 23, 23, 34, 39],
       [55, 13,  7,  1, 50, 25, 39, 47],
       [ 3,  9, 21, 30, 57, 46, 52,  7],
       [ 0, 43,  4, 42, 33, 36, 42, 56],
       [52, 16, 35, 45, 21, 55,  2, 30],
       [21, 29, 46, 39, 44, 39, 59, 55]])

## Numpy Indexing and Selection


In [ ]:
#Create array below
data = np.arange(1,17).reshape(4,4)
data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [ ]:
data[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [214]:
data[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [ ]:
secondrow =data[1,0:4]
secondrow[0:4:2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [ ]:
data[0:4,2] = 77 #data[:,2] = 77
data

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 1st row 0 column, 3th row 2nd column.

In [ ]:
np.array([data[1:2,:1],data[3:4,2:3]])

array([[[ 5]],

       [[77]]])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [ ]:
data[2:4:2,1:4:2]

array([[10, 12]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [ ]:
a = data[(data<10)]
b= data[data>12]
a+b

array([78, 79, 81, 18, 20, 85, 25])

In [ ]:
a = data[(data<10)]

array([1, 2, 4, 5, 6, 8, 9])

In [ ]:
b= data[data>12]

array([77, 77, 77, 13, 14, 77, 16])

In [ ]:
a = data[(data<10)]
b= data[data>12]
a+b

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [ ]:
(a+b).std()

29.700546274093877

#### 22. Get the sum of second column from array above

In [ ]:
data#print array here

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
data[:,1:2].sum()

32

#### 23. Get the median,mean and std of 3rd column from array above

In [ ]:
np.median(data[:,3:4])#median 

10.0

In [ ]:
np.mean(data[:,3:4])#mean

10.0

In [ ]:
np.std(data[:,3:4])#std

4.47213595499958

# Pandas Section

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
# https://pypi.python.org/pypi/libarchive
!apt-get -qq install -y libarchive-dev && pip install -U libarchive
import libarchive
# https://pypi.python.org/pypi/pydot
!apt-get -qq install -y graphviz && pip install pydot
import pydot
#colab baya sorun cikartti datayi okuturken o yüzden herseyi indirdim 

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [203]:
veri =pd.read_csv("Salaries.csv")

In [ ]:
veri.head()

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [ ]:
df =pd.DataFrame(veri)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [ ]:
df.describe()

Id        BasePay  ...  Notes  Status
count  148654.000000  148045.000000  ...    0.0     0.0
mean    74327.500000   66325.448841  ...    NaN     NaN
std     42912.857795   42764.635495  ...    NaN     NaN
min         1.000000    -166.010000  ...    NaN     NaN
25%     37164.250000   33588.200000  ...    NaN     NaN
50%     74327.500000   65007.450000  ...    NaN     NaN
75%    111490.750000   94691.050000  ...    NaN     NaN
max    148654.000000  319275.010000  ...    NaN     NaN

[8 rows x 10 columns]

**How many different year value are there**

In [ ]:
df["Year"].nunique()

4

**Print out max and avg Totalpay**

In [ ]:
df["TotalPay"].max()

567595.43

In [ ]:
df["TotalPay"].mean()

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [ ]:
a =df[(df["TotalPay"])>(df["TotalPay"].mean())]
len(a.index)
#a.shape[0]
#a[a.columns[0]].count()

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [ ]:
df.iloc[2, [8]]

TotalPayBenefits    335280
Name: 2, dtype: object

**Who is lowest paid person**

In [ ]:
a=df.sort_values("TotalPayBenefits", )
b=a.iloc[0]
#lowestpaid = b.iloc[1:2]
#lowestpaid
b[[0,1]]

Id                 148654
EmployeeName    Joe Lopez
Name: 148653, dtype: object

**What are the unique Jobs in dataset?**

In [200]:
df['JobTitle'].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [ ]:
df.JobTitle.value_counts().tail(3)

TRANSIT PAINT SHOP SUPERVISOR I         1
ASSOCIATE HUMAN RESOURCES ANALYST       1
ASSISTANT COURT REPORTER COORDINATOR    1
Name: JobTitle, dtype: int64

In [ ]:
df.JobTitle.value_counts().tail(15)#Not hocam dikkat ederseniz tek dogru cevabi yok o yüzden son 15 yazdirdim cevapla uyusmuyor diye yanlis sanilmasin

ELECTROENCEPHALOGRAPH TECHNICIAN I                    1
Sheriff                                               1
BRAILLIST                                             1
Cashier 3                                             1
FARMER                                                1
ROOFER SUPERVISOR I                                   1
ASSISTANT TO THE DIRECTOR, PUBLIC AFFAIRS       RS    1
HH Mechanical Shop Sprv                               1
PIANIST                                               1
PRINCIPAL RECREATION SUPERVISOR                       1
TRANSIT POWER LINE WORKER SUPERVISOR II               1
POWERHOUSE ELECTRICIAN SUPERVISOR II                  1
TRANSIT PAINT SHOP SUPERVISOR I                       1
ASSOCIATE HUMAN RESOURCES ANALYST                     1
ASSISTANT COURT REPORTER COORDINATOR                  1
Name: JobTitle, dtype: int64

LEGISLATION CLERK                    1
Sheriff                              1
MATERIALS AND SUPPLIES SUPERVISOR    1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [ ]:
allyear = df.Year.where((df["TotalPayBenefits"])>(df["TotalPayBenefits"].mean())).value_counts()
allyear[[2012]]

2012    20366
Name: Year, dtype: int64

**How many people have the word Manager in their job title?**

In [212]:
veri =pd.read_csv("Salaries.csv")

In [239]:

numberofmanager =veri[veri.JobTitle.str.contains(pat='manager', case=False)]
len(numberofmanager.index) 

4110

In [238]:

numbermanager=df[df.apply(lambda row: row.astype(str).str.contains(pat='manager' ,case=False),axis=1)]#use apply function here
len(numbermanager['JobTitle'].index)

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [ ]:
sal_newdf=df.iloc[:,[0,1,2,7,8]]
sal_newdf

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0            1     NATHANIEL FORD  ...  567595.43         567595.43
1            2       GARY JIMENEZ  ...  538909.28         538909.28
2            3     ALBERT PARDINI  ...  335279.91         335279.91
3            4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4            5    PATRICK GARDNER  ...  326373.19         326373.19
...        ...                ...  ...        ...               ...
148649  148650      Roy I Tillery  ...       0.00              0.00
148650  148651       Not provided  ...       0.00              0.00
148651  148652       Not provided  ...       0.00              0.00
148652  148653       Not provided  ...       0.00              0.00
148653  148654          Joe Lopez  ...    -618.13           -618.13

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [ ]:
sal_newdfo=sal_newdf.loc[:,"EmployeeName":"TotalPayBenefits"]
sal_newdfo

EmployeeName  ... TotalPayBenefits
0          NATHANIEL FORD  ...        567595.43
1            GARY JIMENEZ  ...        538909.28
2          ALBERT PARDINI  ...        335279.91
3       CHRISTOPHER CHONG  ...        332343.61
4         PATRICK GARDNER  ...        326373.19
...                   ...  ...              ...
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00
148653          Joe Lopez  ...          -618.13

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [ ]:
employeesmittel = df.where(((df["TotalPayBenefits"])<(df["TotalPayBenefits"].mean()))&((df["TotalPayBenefits"])>(df["TotalPayBenefits"].min())))
employeesmittel["EmployeeName"]

0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN
              ...      
148649    Roy I Tillery
148650     Not provided
148651     Not provided
148652     Not provided
148653              NaN
Name: EmployeeName, Length: 148654, dtype: object

0            NATHANIEL FORD
1              GARY JIMENEZ
2            ALBERT PARDINI
3         CHRISTOPHER CHONG
4           PATRICK GARDNER
                ...        
148649        Roy I Tillery
148650         Not provided
148651         Not provided
148652         Not provided
148653            Joe Lopez
Name: EmployeeName, Length: 148654, dtype: object