<a href="https://colab.research.google.com/github/nadireus/Clarusway/blob/main/Statistics_Assignment_2_C9224Nadire.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [25]:
import numpy as np
import pandas as pd
import scipy.stats
from scipy import stats

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [4]:

samples=np.random.normal(100, 15, 1000)


Compute the **mean**, **median**, and **mode**

In [15]:
mean =np.mean(samples)
median =np.median(samples)
mode =stats.mode(samples)
print(f"mean = {mean}")
print(f"median = {median}")
print(f"mode = {mode}")

mean = 99.75526589266966
median = 100.0946175488269
mode = ModeResult(mode=array([50.1641704]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [17]:
min = np.min(samples)
max =np.max(samples)
q1 = np.percentile(samples, 25, interpolation = 'midpoint')
q3 = np.percentile(samples, 75, interpolation = 'midpoint')
iqr =q3-q1

print(f" min = {min}, max= {max}, q1= {q1}, q3= {q3}, iqr= {iqr}")

 min = 50.164170395388595, max= 139.0721424151618, q1= 89.97089438369562, q3= 109.0268380328174, iqr= 19.055943649121772


In [20]:
iqr_2way = stats.iqr(samples)
iqr_2way

19.024345710960162

Compute the **variance** and **standard deviation**

In [18]:
variance = np.var(samples)
std_dev =np.std(samples)

Compute the **skewness** and **kurtosis**

In [22]:
skewness =stats.skew(samples)
kurtosis =stats.kurtosis(samples)
print(f" skewness = {skewness}, kurtosis= {kurtosis}")

 skewness = -0.13531004433659277, kurtosis= -0.10956365854966421


## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [5]:
x = np.arange(10, 20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [4]:
y = np.array(np.mat('1 2 3 4 5 6 7 8 9 10'))
y

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [7]:
r = np.corrcoef(x,y)
r

array([[1., 1.],
       [1., 1.]])

## Pandas Correlation Calculation

Run the code below

In [8]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

In [9]:
xy = pd.DataFrame({'x-values': x, 'y-values': y})

Call the relevant method  to calculate Pearson's r correlation.

In [11]:
r =x.corr(y)
r

0.7586402890911867

In [13]:
corr_matrix = xy.corr()
corr_matrix

x-values  y-values
x-values   1.00000   0.75864
y-values   0.75864   1.00000

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [20]:
rho, p = scipy.stats.spearmanr(x, y)

print(f" rho= {rho}, p ={p}")

 rho= 0.9757575757575757, p =1.4675461874042197e-06


## Seaborn Dataset Tips

Import Seaborn Library

In [21]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [22]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [23]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [24]:
corr_matrix = tips.corr()
corr_matrix

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000